fixes:
  - 'lib/application/::flutter_bloc/lib/application'
  - 'lib/domain/::flutter_bloc/lib/domain'
  - 'lib/presentation/::flutter_bloc/lib/presentation'
# flags:
#   flutter_bloc:
#     paths:
#       - /flutter_bloc
#   states_rebuilder_example:
#     paths:
#       - /states_rebuilder_example
# coverage:
#   status:
#     project:
#       default:
#         flags:
#           - flutter_bloc
#           - states_rebuilder_example
#       projectA:
#         flags:
#           - flutter_bloc
#       projectB:
#         flags:
#           - states_rebuilder_example
